# Unsupervised Tasks: Bike Trip and Stations Profiles

In [1]:
import pandas as pd

# 1.1 bike_types DEA

In [12]:
df_bike_types = pd.read_csv("../csv/bike_types.csv")
df_bike_types.head()

,id,vehicle_image,name,description,form_factor,rider_capacity,propulsion_type,max_range,battery_capacity
0,152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df_bike_types.shape

(121, 9)

In [18]:
df_bike_types.info()

<class 'pandas.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                121 non-null    int64
 1   vehicle_image     91 non-null     str
 2   name              91 non-null     str
 3   description       51 non-null     str
 4   form_factor       91 non-null     str
 5   rider_capacity    91 non-null     float64
 6   propulsion_type   91 non-null     str
 7   max_range         15 non-null     float64
 8   battery_capacity  22 non-null     float64
dtypes: float64(3), int64(1), str(5)
memory usage: 25.7 KB

In [23]:
df_bike_types["name"].unique()

<ArrowStringArray>
[                              nan,                         'Comfort',
   'Rower z fotelikiem dziecięcym',                          'Tandem',
                 'Elektricno kolo',                     'e-CARGObike',
            'Rowerek dziecięcy 6+',     '3-rychlostní SMARTbike 2.0.',
       'e-SMARTbike 2.0 with RFID',         '28 Zoll - Tourenfahrrad',
                'e-SMARTbike 2.0.',          'Smartbike 2.0 (B) 2019',
                 'e-SMARTbike 1.0',                       'UsedomRad',
               'UsedomRad Classic',         '20 Zoll - Kinderfahrrad',
         '24 Zoll - Kinderfahrrad',                 'Z wałem kardana',
          '7-rychlostní SMARTbike',                 'e-Bike "LaBigi"',
                          'E-Bike',     '7-rychlostní SMARTbike 2.0.',
                     'e-Cargobike',                       'CARGObike',
     '8-rychlostní SMARTbike 2.0.',                  'with Framelock',
          '8-rychlostní SMARTbike',            'CARGObike (3 wheels)',
               '+ Children's seat',         '26 Zoll - Tourenfahrrad',
                           'Cargo',                         'Unknown',
              'E-CLASSICbike SWAP',                        'Handbike',
            'Bike with child seat',       'ebike [električni bicikl]',
                'Dječja sjedalica',                 'CLASSICbike 2.0',
                         'Classic',                'Rower Trójkołowy',
 'e-SMARTbike 2.0 (fixed battery)',                     'CLASSICbike',
            'e-SMARTbike 2.0 RFID',          'SMARTbike 2.0 (A) 2018',
                  'with Fork lock',              'Comfort 1 1/8 Zoll',
          '3-rychlostní SMARTbike']
Length: 47, dtype: str

In [24]:
df_bike_types["propulsion_type"].unique()

<ArrowStringArray>
[nan, 'human', 'electric_assist']
Length: 3, dtype: str

In [25]:
df_bike_types["form_factor"].unique()

<ArrowStringArray>
[nan, 'bicycle', 'cargo_bicycle', 'other']
Length: 4, dtype: str

In [13]:
df_bikes = pd.read_csv("../csv/bikes.csv")
df_bikes.head()

       id  bike_type_id  computer_id
0  400481           196  83300002927
1  374044           204   7551171765
2  373778           204   7551140444
3   34749            14            0
4   88359           143   7551052355

In [14]:
df_cities = pd.read_csv("../csv/cities.csv")
df_cities.head()

,id,name,lat,lon,timezone,country,return_to_official_only
0,220,Zagreb,45.7984,15.98810,Europe/Berlin,HR,True
1,431,Kalisz,51.7525,18.03410,Europe/Warsaw,PL,True
2,199,Innsbruck,47.2632,11.39610,Europe/Berlin,AT,True
3,519,Siemianowice Śląskie,50.3031,19.02220,Europe/Warsaw,PL,True
4,21,Karlsruhe,49.0102,8.41827,Europe/Berlin,DE,False

In [15]:
df_stations_status = pd.read_csv("../csv/stations_status.csv")
df_stations_status.head()

,station_id,time,bikes,booked_bikes,bikes_available_to_rent,free_racks,free_special_racks,maintenance
0,101896428,1.661530e+09,2,0,2,0,0,False
1,54643,1.661531e+09,1,0,1,0,0,False
2,6201611,1.661531e+09,3,0,3,0,0,False
3,294346,1.661531e+09,8,0,8,0,0,False
4,781866,1.661531e+09,1,1,0,5,0,False

In [16]:
df_stations = pd.read_csv("../csv/stations.csv")
df_stations.head()

,id,city_id,name,app_number,terminal_type,place_type,bike_racks,special_racks,rack_locks,lon,lat
0,142186362,135,BIKE 500100,0,NaN,12,0,0,NaN,7.821669,51.677449
1,940986,176,Bahnhof Trassenmoor 5525,5525,NaN,0,6,0,NaN,13.868973,54.090538
2,93646685,176,Mutter/Vater-Kind-Kurklinik Haus Möwennest Zin...,5529,stele,0,15,0,NaN,13.918970,54.073088
3,111365509,243,Station Road,8494,smart_sign,0,20,0,NaN,-3.936120,56.119272
4,405835,302,Birkirkara Road,6868,sign,0,6,0,NaN,14.481456,35.906836

In [17]:
df_trips_small = pd.read_csv("../csv/trips_small.csv")
df_trips_small.head()

,bike_id,city_id,time_start,lon_start,lat_start,lon_end,lat_end,station_id_start,station_id_end,battery_start,battery_end,duration,distance
0,11462,7,1.669377e+09,8.253932,50.069332,8.253393,50.070504,126084480.0,NaN,NaN,NaN,360.0,135.879806
1,11462,7,1.669897e+09,8.242628,50.071337,8.216180,50.095700,87796472.0,4775153.0,NaN,NaN,1920.0,3301.514764
2,11462,7,1.670252e+09,8.216180,50.095700,8.217791,50.095744,4775153.0,NaN,NaN,NaN,780.0,115.020620
3,11462,7,1.670349e+09,8.226448,50.076546,8.249343,50.078160,4775087.0,87796883.0,NaN,NaN,540.0,1643.609250
4,11462,7,1.671514e+09,8.249343,50.078160,8.242628,50.071337,87796883.0,87796472.0,NaN,NaN,4680.0,897.351993